# Generated by Django 5.1.6 on 2026-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('message_imezimwa', models.CharField(default='Huduma ya Shamba Mfukoni haipo kwa sasa. Jaribu baadaye.', max_length=255)),
            ],
            options={
                'verbose_name': 'USSD Configuration',
            },
        ),
    ]
