# Generated by Django 5.1.6 on 2026-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_customer_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='alerted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Taarifa ya mwisho ilipotumwa — inazuia kurudia', null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='down_since',
            field=models.DateTimeField(blank=True, editable=False, help_text='Tangu lini session imekuwa chini', null=True),
        ),
    ]
