# Generated by Django 5.1.6 on 2026-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("value", models.CharField(blank=True, max_length=400)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alama",
                "verbose_name_plural": "Alama",
            },
        ),
        migrations.CreateModel(
            name="Kazi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker",
                    models.CharField(
                        choices=[
                            ("william", "William — Kiongozi mkuu"),
                            ("ibrahimu", "Ibrahimu — Mhudumu wa wateja"),
                            ("selvester", "Selvester — Afisa mauzo"),
                            ("grace", "Grace — Afisa masoko"),
                            ("diana", "Diana — Fedha na ofisi"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=120, unique=True)),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Kitu kinachohusika, mfano invoice:12",
                        max_length=60,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Juu"), (2, "Kawaida"), (3, "Chini")], default=2
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Inafanyiwa kazi"),
                            ("awaiting", "Inasubiri idhini yako"),
                            ("sent", "Imetumwa"),
                            ("done", "Imekamilika"),
                            ("dismissed", "Imeachwa"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=300)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("none", "—"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("social", "Mitandao ya kijamii"),
                            ("faq", "FAQ ya JamiiBot"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=160)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=40)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("draft", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                ("reminders", models.PositiveSmallIntegerField(default=0)),
                (
                    "pushed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ilipotumwa wILife kuomba idhini",
                        null=True,
                    ),
                ),
                ("wilife_code", models.CharField(blank=True, max_length=12)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.CharField(blank=True, max_length=400)),
            ],
            options={
                "verbose_name": "Kazi",
                "verbose_name_plural": "Kazi",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["worker", "status"], name="wf_kazi_worker_status"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ripoti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("asubuhi", "Mpango wa asubuhi"),
                            ("jioni", "Ripoti ya jioni"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("text", models.TextField()),
                ("delivered", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ripoti",
                "verbose_name_plural": "Ripoti",
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "date"), name="wf_ripoti_kind_date"
                    )
                ],
            },
        ),
    ]
