# Generated by Django 5.1.6 on 2026-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wafanyakazi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mtihani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Unaendelea"),
                            ("done", "Umekamilika"),
                            ("failed", "Umeshindwa"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mtihani wa umahiri",
                "verbose_name_plural": "Mitihani ya umahiri",
                "ordering": ["-created_at"],
            },
        ),
    ]
