# Generated by Django 5.1.6 on 2025-02-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_2',
        ),
    ]
