# Generated by Django 5.2 on 2026-03-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_team_facebook_link_team_instagram_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
