# Generated by Django 5.2 on 2026-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_managed_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnotification',
            name='notification_type',
            field=models.CharField(choices=[('payment_reminder', '💰 Payment Reminder'), ('payment_received', '✅ Payment Received'), ('suspension_warning', '⚠️ Suspension Warning'), ('suspension', '🔴 Website Suspended'), ('restoration', '🟢 Website Restored'), ('maintenance', '🔧 Maintenance Notice'), ('update', '📢 General Update'), ('invoice', '🧾 Invoice'), ('support', '🎧 Support Request'), ('general', '✉️ General Message'), ('custom', '✉️ Custom Message')], default='custom', max_length=30),
        ),
    ]
