# Generated by Django 5.2 on 2026-03-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_hosting_config_dns'),
        ('apps', '0012_merge_20260308_0236'),
    ]

    operations = [
    ]
