# Generated by Django 5.2 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_merge_20260308_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientnotification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Client Notification', 'verbose_name_plural': 'Client Notifications'},
        ),
        migrations.AlterModelOptions(
            name='hostingpayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Hosting Payment', 'verbose_name_plural': 'Hosting Payments'},
        ),
        migrations.AlterModelOptions(
            name='managedwebsite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Managed Website', 'verbose_name_plural': 'Managed Websites'},
        ),
        migrations.AlterModelOptions(
            name='scheduledaction',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'Scheduled Action', 'verbose_name_plural': 'Scheduled Actions'},
        ),
        migrations.AlterModelOptions(
            name='websitefeature',
            options={'verbose_name': 'Website Feature', 'verbose_name_plural': 'Website Features'},
        ),
        migrations.AlterField(
            model_name='service',
            name='Service_type',
            field=models.CharField(db_column='Service_type', max_length=255),
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Service_type',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='clientnotification',
            name='notification_type',
            field=models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('suspension_warning', 'Suspension Warning'), ('suspension', 'Website Suspended'), ('restoration', 'Website Restored'), ('maintenance', 'Maintenance Notice'), ('update', 'General Update'), ('invoice', 'Invoice'), ('support', 'Support Request'), ('general', 'General Message'), ('custom', 'Custom Message')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='hostingpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hostingpayment',
            name='months_covered',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hostingpayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hostingpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hostingpayment',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='auto_suspend_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='hosting_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='hosting_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='send_expiry_warnings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='site_type',
            field=models.CharField(choices=[('django', 'Django Website'), ('static', 'Static HTML/CSS'), ('wordpress', 'WordPress'), ('other', 'Other')], default='django', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='suspension_message',
            field=models.TextField(blank=True, default='This service has been temporarily suspended. Please contact the administrator.'),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='managedwebsite',
            name='warning_days_before',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='action_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='action_type',
            field=models.CharField(choices=[('suspend', 'Suspend Website'), ('restore', 'Restore Website'), ('maintenance', 'Enable Maintenance Mode'), ('send_email', 'Send Email'), ('disable_feature', 'Disable Feature'), ('enable_feature', 'Enable Feature')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitefeature',
            name='disabled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websitefeature',
            name='feature_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websitefeature',
            name='feature_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='websitefeature',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
