# Generated by Django 5.1.6 on 2026-07-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_websitetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='db_host',
            field=models.CharField(default='db.jamiitek.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='ftp_host',
            field=models.CharField(default='ftp.jamiitek.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='server_hostname',
            field=models.CharField(default='srv1.jamiitek.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='badge',
            field=models.CharField(blank=True, choices=[('HOT', '🔥 HOT'), ('NEW', '✨ NEW'), ('PRO', '⭐ PRO'), ('', 'No Badge')], max_length=10, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='category',
            field=models.CharField(choices=[('restaurant', '🍽️ Restaurant'), ('salon', '💅 Salon & Beauty'), ('hotel', '🏨 Hotel & Lodging'), ('shop', '🛒 Shop / Duka'), ('clinic', '🏥 Clinic & Healthcare'), ('church', '⛪ Church & Religion'), ('school', '🎓 School & Education'), ('portfolio', '🎨 Portfolio & Personal'), ('Tourism', '🎨 Safari & Travel website'), ('Real Estate', '🎨 Real Estate'), ('Technology', '🎨 Technology'), ('admin', '🎨 Admin & Dashboard'), ('Booking', '🎨 Booking system'), ('Real Estate', '🎨 Real Estate'), ('Landing', '🎨 Landing Page'), ('niche', '🎨 Special Premium niche'), ('Media', '🎨 Media & News'), ('other', '🌐 Other')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='description',
            field=models.TextField(verbose_name='Description (Short)'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='gradient_end',
            field=models.CharField(default='#ff6584', max_length=20, verbose_name='Card Color End'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='gradient_start',
            field=models.CharField(default='#6c63ff', max_length=20, verbose_name='Card Color Start'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='preview_html',
            field=models.TextField(help_text='Weka HTML code yote ya template hapa. Itaonekana kwenye preview page automatically.', verbose_name='Preview HTML Code'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='price_hosted_monthly',
            field=models.IntegerField(default=30000, verbose_name='Hosted Monthly Price (TSh)'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=2, verbose_name='Rating'),
        ),
    ]
