# Generated by Django 5.1.6 on 2026-07-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_hostingconfiguration_db_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version, e.g. how-to-build-website-tanzania', max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary (shows on blog list + social shares + Google). 150-300 chars ideal.', max_length=320)),
                ('body', models.TextField(help_text='Full article. Supports HTML. Write 800-1500 words for best SEO.')),
                ('cover_image', models.URLField(blank=True, help_text='Cover image URL (Uploadcare/Cloudinary). 1200x630 ideal for social sharing.')),
                ('meta_title', models.CharField(blank=True, help_text='Custom <title> (defaults to post title). Keep under 60 chars.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Custom meta description (defaults to excerpt). 150-160 chars ideal.', max_length=170)),
                ('focus_keyword', models.CharField(blank=True, help_text='Main keyword this post targets, e.g. "website builder Tanzania"', max_length=100)),
                ('author_name', models.CharField(default='JamiiTek', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show at top of blog')),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='apps.blogcategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
