# Generated by Django 5.1.6 on 2026-03-13 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(help_text='e.g. Amara, Juma, Helper', max_length=100)),
                ('business_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What does this bot do? Describe its main purpose.')),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('sw+en', 'Swahili + English (auto-detect)')], default='sw+en', max_length=10)),
                ('tone', models.CharField(choices=[('professional', 'Professional & Formal'), ('friendly', 'Friendly & Warm'), ('casual', 'Casual & Fun'), ('formal', 'Very Formal')], default='friendly', max_length=20)),
                ('greeting_msg', models.TextField(help_text='First message when user says hi')),
                ('fallback_msg', models.TextField(default='Samahani, sijaelewea vizuri. Tafadhali uliza tena au piga simu +255XXX.')),
                ('human_handoff_msg', models.TextField(default='Nitakupeleka kwa mtu wa kweli sasa hivi. Subiri kidogo...', help_text='Message when bot cannot handle and transfers to human')),
                ('whatsapp_number', models.CharField(blank=True, help_text='e.g. +255750123456', max_length=20)),
                ('whatsapp_phone_id', models.CharField(blank=True, help_text='Meta Phone Number ID', max_length=50)),
                ('whatsapp_token', models.CharField(blank=True, help_text='WhatsApp Cloud API token', max_length=500)),
                ('webhook_verify_token', models.CharField(blank=True, editable=False, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft — Not deployed'), ('active', 'Active — Running'), ('suspended', 'Suspended — Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.CharField(default='claude-sonnet-4-5', max_length=60)),
                ('ai_temperature', models.FloatField(default=0.7, help_text='0=strict, 1=creative')),
                ('max_context_msgs', models.PositiveSmallIntegerField(default=10, help_text='Messages to remember in conversation')),
                ('collect_name', models.BooleanField(default=True, help_text='Ask for customer name at start')),
                ('collect_phone', models.BooleanField(default=False, help_text='Ask for customer phone')),
                ('admin_suspended_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('price_tzs', models.PositiveIntegerField(help_text='Monthly price in TZS')),
                ('msg_limit', models.PositiveIntegerField(help_text='Messages per month (0=unlimited)')),
                ('max_services', models.PositiveIntegerField(default=10, help_text='Max services/FAQs')),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='chatbot.botconfig')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BotService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Website Design', max_length=150)),
                ('description', models.TextField(help_text='Describe this service in detail')),
                ('price', models.CharField(blank=True, help_text='e.g. TZS 500,000 or Free', max_length=100)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated trigger words', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='chatbot.botconfig')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active'), ('overdue', 'Overdue'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('messages_used', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='chatbot.botconfig')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(default='Tanzania', max_length=60)),
                ('city', models.CharField(default='Dar es Salaam', max_length=60)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Client',
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='chatbot.chatbotclient'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('wa_contact_name', models.CharField(blank=True, help_text='Name from WhatsApp profile', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('is_human_handoff', models.BooleanField(default=False, help_text='Transferred to human agent')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.botconfig')),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('bot', 'customer_phone')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'Bot'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, max_length=60)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='AI response time in ms')),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='TZS')),
                ('months_covered', models.PositiveSmallIntegerField(default=1)),
                ('payment_method', models.CharField(default='NMB Bank Transfer', max_length=60)),
                ('transaction_ref', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='chatbot.botsubscription')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bot_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('messages_in', models.PositiveIntegerField(default=0)),
                ('messages_out', models.PositiveIntegerField(default=0)),
                ('new_conversations', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('avg_latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('handoffs', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot.botconfig')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('bot', 'date')},
            },
        ),
    ]
