# Generated by Django 5.1.6 on 2026-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — Not deployed'), ('pending', 'Pending — Awaiting Phone ID setup'), ('active', 'Active — Running'), ('suspended', 'Suspended — Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
