# Generated by Django 5.1.6 on 2026-09-13 12:32

"""
Handoff kamili: kusimama, kuarifu, na amri za mmiliki.

Zamani `is_human_handoff = True` iliwekwa na hakuna kilichofuata.
Sasa mazungumzo yanabeba historia yake, na `owner_whatsapp`
inapokea taarifa.

`owner_whatsapp` inajazwa kutoka namba aliyojisajili nayo mteja —
bila hiyo, bot zilizopo zingesimama bila mtu wa kuarifiwa.
"""
from django.db import migrations, models


def fill_owner_numbers(apps, schema_editor):
    """Namba ya mmiliki = aliyojisajili nayo, kama haijawekwa."""
    BotConfig = apps.get_model('chatbot', 'BotConfig')
    for bot in BotConfig.objects.select_related('client').iterator():
        phone = (bot.client.phone or '').strip()
        if phone and not bot.owner_whatsapp:
            bot.owner_whatsapp = phone[:20]
            bot.save(update_fields=['owner_whatsapp'])


def noop(apps, schema_editor):
    """Kurudi nyuma hakuhitaji kitu — field yenyewe inaondoka."""


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_baileys_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='notify_handoff',
            field=models.BooleanField(default=True, help_text='Tuma taarifa mteja anapohitaji binadamu'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='owner_whatsapp',
            field=models.CharField(blank=True, help_text='Namba ya mmiliki inayopokea taarifa. Mfano: +255750123456', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_by',
            field=models.CharField(blank=True, choices=[('customer', 'Mteja aliomba'), ('ai', 'Bot ilishindwa'), ('owner', 'Mmiliki alisimamisha')], max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_count',
            field=models.PositiveIntegerField(default=0, help_text='Mara ngapi mazungumzo haya yamehitaji binadamu'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_notified_at',
            field=models.DateTimeField(blank=True, help_text='Mmiliki alipoarifiwa', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.RunPython(fill_owner_numbers, noop),
    ]
