# Generated by Django 5.1.6 on 2026-09-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Swali la mteja kama alivyoliandika')),
                ('normalized', models.CharField(db_index=True, help_text='Kwa kuunganisha maswali yanayofanana', max_length=300)),
                ('source', models.CharField(choices=[('fallback', 'Bot ilikwama'), ('unsure', 'Bot haikujua'), ('handoff', 'Mteja alihitaji binadamu')], default='unsure', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Bado — hakuna jibu'), ('drafted', 'Rasimu iko tayari'), ('answered', 'Imejibiwa'), ('dismissed', 'Imepuuzwa')], default='open', max_length=12)),
                ('times_asked', models.PositiveIntegerField(default=1)),
                ('first_asked_at', models.DateTimeField(auto_now_add=True)),
                ('last_asked_at', models.DateTimeField(auto_now=True)),
                ('bot_reply', models.TextField(blank=True, help_text='Bot ilijibu nini wakati ule')),
                ('suggested_answer', models.TextField(blank=True, help_text='Rasimu ya AI — bado haijatumika')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gaps', to='chatbot.botconfig')),
                ('created_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.botfaq')),
                ('example_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
            ],
            options={
                'ordering': ['-times_asked', '-last_asked_at'],
                'indexes': [models.Index(fields=['bot', 'status'], name='chatbot_kno_bot_id_67add6_idx')],
                'unique_together': {('bot', 'normalized')},
            },
        ),
    ]
