# Generated by Django 5.1.6 on 2026-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_knowledge_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='memory',
            field=models.TextField(blank=True, help_text='Mambo yanayodumu kuhusu mteja huyu — yanaingia kwenye kila jibu'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory_at_count',
            field=models.PositiveIntegerField(default=0, help_text='Ilikuwa jumbe ngapi kumbukumbu ilipoandikwa mwisho'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='memory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
