# Generated by Django 5.1.6 on 2026-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_session_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='owner_lid',
            field=models.CharField(blank=True, editable=False, help_text='LID ya mmiliki, imetafsiriwa kutoka namba. WhatsApp inatumia LID badala ya namba kwa wateja wengi.', max_length=25),
        ),
    ]
