# Generated by Django 5.1.6 on 2026-09-18 10:47

"""
Chaguo-msingi za jumbe.

`fallback_msg` ilikuwa na "piga simu +255XXX" — namba BANDIA
iliyokuwa inatumwa kwa wateja halisi kila bot iliposhindwa kuelewa
swali. Bot zilizopo bado zinayo kwenye database, kwa hiyo
tunaisafisha.

Ujumbe ambao mmiliki ameubadilisha mwenyewe hauguswi — tunabadilisha
ule wa chaguo-msingi pekee.
"""
from django.db import migrations, models

OLD = "Samahani, sijaelewea vizuri. Tafadhali uliza tena au piga simu +255XXX."
NEW = "Samahani, sijaelewa vizuri. Tafadhali uliza kwa njia nyingine."


def clean_fake_number(apps, schema_editor):
    BotConfig = apps.get_model('chatbot', 'BotConfig')
    # Ule wa chaguo-msingi haswa
    BotConfig.objects.filter(fallback_msg=OLD).update(fallback_msg=NEW)
    # Na wowote uliobaki wenye namba bandia
    for bot in BotConfig.objects.filter(fallback_msg__contains='+255XXX'):
        bot.fallback_msg = NEW
        bot.save(update_fields=['fallback_msg'])


def noop(apps, schema_editor):
    """Hakuna cha kurudisha — hatutaki namba bandia irudi."""



class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_usage_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='fallback_msg',
            field=models.TextField(default='Samahani, sijaelewa vizuri. Tafadhali uliza kwa njia nyingine.'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='greeting_msg',
            field=models.TextField(blank=True, default='Karibu {name}! Nitakusaidiaje leo?', help_text='Ujumbe wa kwanza. {name} inabadilishwa na jina la mteja.'),
        ),

        migrations.RunPython(clean_fake_number, noop),
    ]
