# Generated by Django 5.1.6 on 2026-07-14 01:10

import builder.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(unique=True, validators=[builder.models.validate_subdomain])),
                ('website_type', models.CharField(default='companyprofile', max_length=50)),
                ('site_name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadcare_url', models.URLField()),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='builder.clientwebsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('name_singular', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('fields', models.JSONField(default=list)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='builder.clientwebsite')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('website', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.clientwebsite')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='builder_aiu_user_id_26caa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('data', models.JSONField(default=dict)),
                ('image_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='builder.sitecollection')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('collection', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='home', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('grapes_data', models.JSONField(blank=True, default=dict)),
                ('html_cache', models.TextField(blank=True)),
                ('css_cache', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='builder.clientwebsite')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
                'unique_together': {('website', 'slug')},
            },
        ),
    ]
