# Generated by Django 5.1.6 on 2026-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsite',
            name='global_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='nav_layout',
            field=models.CharField(choices=[('topnav', 'Top Navigation'), ('sidenav', 'Side Navigation')], default='topnav', max_length=10),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='template_key',
            field=models.CharField(default='clean_start', max_length=50),
        ),
    ]
