# Generated by Django 5.1.6 on 2026-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_clientwebsite_global_css_clientwebsite_nav_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsite',
            name='accent_color',
            field=models.CharField(default='#e8a13c', max_length=9),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='content_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='dark_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='nav_style',
            field=models.CharField(choices=[('top', 'Top Navbar (classic)'), ('glass', 'Floating Glass Navbar'), ('side', 'Side Navbar (dashboard style)'), ('center', 'Centered Minimal')], default='glass', max_length=12),
        ),
    ]
