# Generated by Django 5.1.6 on 2026-07-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_clientwebsite_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsite',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g. www.mybusiness.co.tz — bila http://', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium sites can connect a custom domain.'),
        ),
        migrations.CreateModel(
            name='SiteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('people_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='builder.siteitem')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='builder.clientwebsite')),
            ],
            options={
                'verbose_name_plural': 'Site inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
