# Generated by Django 5.1.6 on 2026-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_clientwebsite_custom_domain_clientwebsite_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsite',
            name='custom_footer_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='custom_nav_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='nav_preset',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
