# Generated by Django 5.1.6 on 2026-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_supabase_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwebsite',
            name='domain_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='domain_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='domain_message',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='clientwebsite',
            name='domain_status',
            field=models.CharField(blank=True, choices=[('pending', 'Inasubiri DNS'), ('dns_ok', 'DNS sawa — SSL inatengenezwa'), ('active', 'Live'), ('error', 'Tatizo')], default='', max_length=10),
        ),
    ]
