# Generated by Django 5.1.6 on 2026-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_custom_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='code_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='code_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='code_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='mode',
            field=models.CharField(choices=[('visual', 'Visual editor'), ('code', 'Code yangu')], default='visual', max_length=10),
        ),
    ]
