# Generated by Django 5.1.6 on 2026-09-30 04:40

"""
Top bar (Floating Glass) ndiyo header ya default ya site mpya — sidebar ya
kushoto ilichukua sehemu kubwa ya skrini ya laptop.

Site zilizopo zenye sidebar ya DEFAULT (side_classic, na mmiliki hajawahi
kuhifadhi hatua ya Header kwenye Studio) zinahamishwa kwenye top bar.
Aliyechagua sidebar mwenyewe anabaki nayo.
"""
from django.db import migrations, models


def to_top_bar(apps, schema_editor):
    Site = apps.get_model('builder', 'ClientWebsite')
    for site in Site.objects.filter(nav_preset='side_classic').only('id', 'theme_settings'):
        done = (site.theme_settings or {}).get('studio_done', [])
        if 'header' not in done:
            Site.objects.filter(pk=site.pk).update(nav_preset='top_glass')


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0012_relax_unknown_not_null_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientwebsite",
            name="nav_preset",
            field=models.CharField(blank=True, default="top_glass", max_length=20),
        ),
        migrations.RunPython(to_top_bar, migrations.RunPython.noop),
    ]
