# Generated by Django 5.1.6 on 2026-09-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0008_code_studio"),
        ("builder", "0013_default_top_header"),
    ]

    operations = []
