# Generated by Django 5.1.6 on 2025-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
