# Generated by Django 5.1.6 on 2025-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_websitetype_client_projectproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='pdf_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
