# Generated by Django 5.2 on 2026-03-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_add_linkedin_to_team'),
        ('apps', '0011_domain_email_hosting'),
    ]

    operations = [
    ]
