# Generated by Django 5.1.6 on 2026-07-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=48, unique=True)),
                ('title', models.CharField(default='Service Agreement', help_text='e.g. Website Development Agreement', max_length=200)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField(blank=True, help_text='Contract text in English (HTML). AI can draft this.')),
                ('body_sw', models.TextField(blank=True, help_text='Contract text in Swahili (HTML). AI can draft this.')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. 50% deposit, 50% on completion', max_length=300)),
                ('timeline', models.CharField(blank=True, help_text='e.g. 3 weeks from deposit', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to client'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('provider_name', models.CharField(default='JamiiTek', max_length=120)),
                ('provider_rep', models.CharField(default='', help_text='Your name as the signing representative', max_length=120)),
                ('signed_name', models.CharField(blank=True, max_length=160)),
                ('signed_email', models.EmailField(blank=True, max_length=254)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_language', models.CharField(blank=True, max_length=2)),
                ('signature_data', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='apps.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
