# Generated by Django 6.0.7 on 2026-07-30 22:08

import apps.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_hosting_duration_discounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='provider_rep',
            field=models.CharField(default='W. Chipindi', help_text='Your name as the signing representative', max_length=120),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_signature',
            field=models.CharField(blank=True, default='W. Chipindi', help_text='Your handwritten-style signature text (e.g. W. Chipindi)', max_length=120),
        ),
        migrations.AlterField(
            model_name='contract',
            name='provider_signed_date',
            field=models.DateField(blank=True, help_text='Date you signed (defaults to creation date)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature_block_en',
            field=models.TextField(blank=True, help_text='Signatures section intro (English). Leave blank for default.'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature_block_sw',
            field=models.TextField(blank=True, help_text='Signatures section intro (Swahili). Leave blank for default.'),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('external_id', models.CharField(help_text='srv-xxx (Render), zone id (Cloudflare), domain (RDAP)', max_length=200)),
                ('credentials', apps.crypto.EncryptedJSONField(help_text='Imefichwa kwa Fernet. Haionekani baada ya kuhifadhi.')),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(blank=True, max_length=60)),
                ('monthly_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('renews_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cached_summary', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='apps.managedwebsite')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['website', 'provider'],
                'unique_together': {('website', 'provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.integration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.managedwebsite')),
            ],
            options={
                'verbose_name': 'Integration audit log',
                'verbose_name_plural': 'Integration audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('metrics', models.JSONField(default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='apps.integration')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['integration', '-checked_at'], name='apps_integr_integra_c019c1_idx')],
            },
        ),
    ]
