# Generated by Django 6.0.7 on 2026-07-30 22:43

from decimal import Decimal

from django.db import migrations, models

FABRICATED = {
    'ip_address': '197.250.10.1',
    'server_hostname': 'srv1.jamiitek.com',
    'ftp_host': 'ftp.jamiitek.com',
    'db_host': 'db.jamiitek.com',
    'server_location': 'Dar es Salaam, Tanzania',
}

# Thamani hizi zilikuwa defaults, si data halisi ya mtu yeyote.
NUMERIC_FABRICATED = {
    'disk_used_gb': Decimal('1.2'),
    'bandwidth_used': Decimal('4.5'),
    'uptime_percent': Decimal('99.97'),
}


def clear_fabricated(apps_registry, schema_editor):
    Cfg = apps_registry.get_model('apps', 'HostingConfiguration')
    cleared = 0
    for cfg in Cfg.objects.all():
        changed = []
        for field, fake in FABRICATED.items():
            if getattr(cfg, field, None) == fake:
                setattr(cfg, field, None if field == 'ip_address' else '')
                changed.append(field)
        for field, fake in NUMERIC_FABRICATED.items():
            val = getattr(cfg, field, None)
            if val is not None and Decimal(str(val)) == fake:
                setattr(cfg, field, None)
                changed.append(field)
        if changed:
            cfg.save(update_fields=changed)
            cleared += 1
    if cleared:
        print(f'  → records {cleared} zimesafishwa')


def restore_noop(apps_registry, schema_editor):
    """Hakuna kurudi nyuma — data ya kubuni hairudishwi."""
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_contract_provider_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='bandwidth_used',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='db_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='disk_used_gb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='ftp_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Acha wazi — inatoka kwa provider ikiwa integration imeunganishwa.', null=True),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='server_hostname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='server_location',
            field=models.CharField(blank=True, default='', help_text='Acha wazi. Usidai data iko Tanzania kama iko nje — PDP Act 2022.', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostingconfiguration',
            name='uptime_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acha wazi — inahesabiwa kutoka snapshots halisi.', max_digits=5, null=True),
        ),

    # ── Data migration: futa thamani za kubuni zilizohifadhiwa ──
    #
    # Kubadilisha default kwenye model hakubadilishi records zilizopo.
    # Hizi ndizo zilizokuwa zinaonyeshwa kwa wateja kama data halisi.

    migrations.RunPython(clear_fabricated, restore_noop),
    ]
