# Generated by Django 5.1.6 on 2026-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_clear_fabricated_hosting_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, help_text='Uploadcare UUID only, e.g. 1a2b3c4d-5e6f-7890-abcd-ef1234567890', max_length=255)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the headline, e.g. "Web Development"', max_length=80)),
                ('headline', models.CharField(help_text='Wrap the accented words in *asterisks*, e.g. "That *Drive Success*"', max_length=120)),
                ('subheadline', models.CharField(blank=True, max_length=260)),
                ('cta_label', models.CharField(blank=True, default='Start Your Project', max_length=40)),
                ('cta_url', models.CharField(blank=True, default='/get-started/', max_length=300)),
                ('cta2_label', models.CharField(blank=True, max_length=40)),
                ('cta2_url', models.CharField(blank=True, max_length=300)),
                ('focal', models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='center', help_text='Which part of the photo stays visible when cropped', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, help_text='Uploadcare UUID only, e.g. 1a2b3c4d-5e6f-7890-abcd-ef1234567890', max_length=255)),
                ('title', models.CharField(max_length=120)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, help_text='e.g. E-Commerce, School System, Tourism', max_length=60)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('live_url', models.URLField(blank=True, help_text='Link to the live site')),
                ('year', models.CharField(blank=True, max_length=9)),
                ('is_featured', models.BooleanField(default=True, help_text='Show in the homepage slider')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, help_text='Uploadcare UUID only, e.g. 1a2b3c4d-5e6f-7890-abcd-ef1234567890', max_length=255)),
                ('quote', models.TextField(max_length=400)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. CEO, Mushi Traders', max_length=140)),
                ('rating', models.IntegerField(choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
