# Generated by Django 5.1.6 on 2026-08-05 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_heroslide_portfolioitem_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, help_text='Auto: RCP-YYYY-NNNN if left blank', max_length=40)),
                ('token', models.CharField(db_index=True, editable=False, max_length=48, unique=True)),
                ('kind', models.CharField(choices=[('full', 'Full payment'), ('deposit', 'Deposit / Advance'), ('balance', 'Balance / Final'), ('partial', 'Part payment')], default='full', max_length=10)),
                ('title', models.CharField(default='Website Development Payment', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short summary of what was built')),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 18 for 18% VAT. Leave blank for none.', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='How much the client actually paid on this receipt', max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigopesa', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='mpesa', max_length=12)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa / bank transaction reference', max_length=120)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('received_by', models.CharField(default='W. Chipindi', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide this receipt from the client portal')),
                ('require_signature', models.BooleanField(default=True, help_text='Ask the client to sign before the PDF downloads')),
                ('signature_data', models.TextField(blank=True, help_text='Base64 PNG of the drawn signature')),
                ('signature_name', models.CharField(blank=True, max_length=160)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='apps.managedwebsite')),
            ],
            options={
                'verbose_name': 'Development Receipt',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
