# Generated by Django 5.1.6 on 2026-08-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_developmentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentreceipt',
            name='client_company_manual',
            field=models.CharField(blank=True, max_length=160, verbose_name='Client company'),
        ),
        migrations.AddField(
            model_name='developmentreceipt',
            name='client_email_manual',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Client email'),
        ),
        migrations.AddField(
            model_name='developmentreceipt',
            name='client_name_manual',
            field=models.CharField(blank=True, max_length=160, verbose_name='Client name'),
        ),
        migrations.AddField(
            model_name='developmentreceipt',
            name='client_phone_manual',
            field=models.CharField(blank=True, max_length=40, verbose_name='Client phone'),
        ),
        migrations.AddField(
            model_name='developmentreceipt',
            name='project_label',
            field=models.CharField(blank=True, help_text='What this receipt is for, when no website is linked. e.g. "Africanberty Tips — Mobile App"', max_length=200),
        ),
        migrations.AlterField(
            model_name='developmentreceipt',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave blank for work not tied to a managed website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='apps.managedwebsite'),
        ),
    ]
