# Generated by Django 5.1.6 on 2026-09-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_developmentreceipt_client_company_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentreceipt',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional. Set this so the receipt appears in the client portal when it is not linked to a website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_receipts', to='apps.client'),
        ),
    ]
