# Generated by Django 5.1.6 on 2026-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_developmentreceipt_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.CharField(blank=True, help_text='URL kamili ya image. Tumia kitufe cha kupakia.', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.CharField(blank=True, help_text='URL kamili ya image. Tumia kitufe cha kupakia.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.CharField(blank=True, help_text='URL kamili ya image. Tumia kitufe cha kupakia.', max_length=255),
        ),
    ]
