# Generated by Django 5.1.6 on 2026-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0030_supabase_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesapalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_reference",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "order_tracking_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("chatbot_subscription", "Chatbot Subscription"),
                            ("hosting_renewal", "Hosting Renewal"),
                            ("invoice", "Invoice Payment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="TZS", max_length=8)),
                ("months", models.PositiveSmallIntegerField(default=1)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Pesapal: 0 INVALID, 1 COMPLETED, 2 FAILED, 3 REVERSED",
                        null=True,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=40)),
                ("confirmation_code", models.CharField(blank=True, max_length=60)),
                ("redirect_url", models.URLField(blank=True, max_length=600)),
                ("fulfilled", models.BooleanField(default=False)),
                ("raw_status", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pesapal Transaction",
                "verbose_name_plural": "Pesapal Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
