# Generated by Django 5.1.6 on 2026-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_seed_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='accent',
            field=models.CharField(default='#2E7BF6', help_text='Badge colour as a hex code, e.g. #2E7BF6', max_length=7),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('code', 'Code — websites'), ('bot', 'Robot — chatbot'), ('server', 'Server — hosting'), ('globe', 'Globe — domains'), ('mobile', 'Phone — mobile apps'), ('design', 'Palette — design'), ('builder', 'Builder — site builder'), ('layout', 'Layout — templates')], default='code', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='link_label',
            field=models.CharField(default='Learn more', max_length=40),
        ),
        migrations.AddField(
            model_name='service',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where the card goes, e.g. /bot/ or #hosting. Empty = the /service/ page.', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Smaller numbers appear first.'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show this service in the homepage "What we build" section.'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, help_text='One or two short sentences for the homepage card. Leave empty to use the start of the description.', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Full description (shown on the /service/ page).'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(db_column='Service_type', max_length=255, verbose_name='Name'),
        ),
    ]
