# Generated by Django 5.1.6 on 2026-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0034_pesapaltransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_news",
            field=models.BooleanField(
                default=False, help_text="Auto-generated news article (AI newsroom)."
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Original news outlet, e.g. BBC, The Citizen.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Original news source (for attribution + dedup).",
                max_length=600,
            ),
        ),
    ]
