# Generated by Django 5.1.6 on 2026-09-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0035_blogpost_is_news_blogpost_source_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Not shown publicly.", max_length=254
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide this comment from the public page.",
                    ),
                ),
                (
                    "is_staff_reply",
                    models.BooleanField(
                        default=False,
                        help_text="Written by the JamiiTek team (shows a badge).",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="apps.blogcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="apps.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
