# Generated by Django 5.1.6 on 2026-09-25 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0036_blogcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text='E.g. "Founder & Editor", "Tech Reporter".',
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="2-4 sentences: experience, what you cover, why readers can trust you.",
                        max_length=1200,
                    ),
                ),
                (
                    "photo",
                    models.URLField(
                        blank=True,
                        help_text="Square photo of the real person (400x400+).",
                    ),
                ),
                ("x_url", models.URLField(blank=True, verbose_name="X / Twitter URL")),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Admin account of this author — their edits are credited automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Real author shown on the article (with bio). Leave empty to credit yourself automatically.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="apps.blogauthor",
            ),
        ),
    ]
