# Generated by Django 5.1.6 on 2026-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedwebsite',
            name='last_warning_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='managedwebsite',
            name='last_warning_stage',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Hatua ya mwisho ya onyo iliyotumwa (7, 3 au 1).', null=True),
        ),
        migrations.AddField(
            model_name='managedwebsite',
            name='suspension_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
