# Generated by Django 5.1.6 on 2026-09-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_expiry_notice_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Aina ya barua, mfano suspension au expiry_warning', max_length=40)),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='messageId kutoka Brevo — inaunganisha na matukio', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Imetumwa'), ('delivered', 'Imefika'), ('opened', 'Imefunguliwa'), ('clicked', 'Amebonyeza link'), ('deferred', 'Imecheleweshwa'), ('bounced', 'Imerudi'), ('spam', 'Spam'), ('blocked', 'Imezuiliwa'), ('error', 'Imeshindwa')], db_index=True, default='sent', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='apps.client')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='apps.managedwebsite')),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='apps_emaill_created_1d6180_idx')],
            },
        ),
    ]
