# Generated by Django 5.1.6 on 2026-09-30 04:57

"""
SEO ya templates: slug (anwani yenye jina — /templates/savanna-luxe/) na
maandishi ya Google. Templates zilizopo zinapewa slug kutoka majina yao.
"""
from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    T = apps.get_model('apps', 'WebsiteTemplate')
    used = set(T.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))
    for t in T.objects.filter(models.Q(slug__isnull=True) | models.Q(slug='')).order_by('pk'):
        base = slugify(t.name)[:200] or 'template'
        slug, n = base, 2
        while slug in used:
            slug, n = f'{base}-{n}', n + 1
        used.add(slug)
        T.objects.filter(pk=t.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0041_clean_email_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitetemplate",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="Maelezo marefu kwenye ukurasa wa template (aya kadhaa). Yanasaidia sana SEO.",
            ),
        ),
        migrations.AddField(
            model_name="websitetemplate",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="Maelezo ya Google (≤155 herufi). Tupu = yanatengenezwa yenyewe.",
                max_length=170,
            ),
        ),
        migrations.AddField(
            model_name="websitetemplate",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Kichwa cha Google (≤60 herufi). Tupu = kinatengenezwa chenyewe.",
                max_length=70,
            ),
        ),
        migrations.AddField(
            model_name="websitetemplate",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Inajazwa yenyewe kutoka jina. Usibadilishe baada ya kuchapishwa (link za Google zingevunjika).",
                max_length=220,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
    ]
