# Generated by Django 5.1.6 on 2026-09-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_template_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesapaltransaction',
            name='plan_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
