# Generated by Django 5.1.6 on 2026-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0046_staff_two_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Default methods (M-Pesa / Bank)"),
                    ("pesapal", "Pesapal (card / mobile money online)"),
                    ("both", "Both"),
                ],
                default="manual",
                help_text="Mteja aone njia za kawaida, Pesapal, au zote",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
