name: Daily Email Notifications

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC = 08:00 EAT kila siku
  workflow_dispatch:        # Kitufe cha manual run kwenye GitHub

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email notifications
        run: python manage.py send_expiry_emails
       - name: Run email notifications
        run: python manage.py send_expiry_emails
        env:
          DATABASE_URL: "postgresql://postgres.frapnewfadymevdkznrq:NyumbaChap@aws-1-eu-north-1.pooler.supabase.com:5432/postgres"
          EMAIL_HOST_USER: "info@jamiitek.com"
          EMAIL_HOST_PASSWORD: "tbgh swtl zple dhiv"
          SECRET_KEY: "django-insecure-@&r$)$xpb)f6pm=_73pupatv2#n-%0%d=(cky=kab5ww6&*tzs"
          DJANGO_SETTINGS_MODULE: ebenezeri.settings      
